# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rj

import flatbuffers

class PCMStatusFrame(object):
    __slots__ = ['_tab']

    # PCMStatusFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PCMStatusFrame
    def Module(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # PCMStatusFrame
    def Enabled(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # PCMStatusFrame
    def PressureSwitchValve(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(5))
    # PCMStatusFrame
    def CompressorCurrent(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # PCMStatusFrame
    def ClosedLoopControl(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # PCMStatusFrame
    def CompressorCurrentTooHighFault(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(17))
    # PCMStatusFrame
    def CompressorShortedFault(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(18))
    # PCMStatusFrame
    def CompressorNotConnectedFault(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(19))

def CreatePCMStatusFrame(builder, module, enabled, pressureSwitchValve, compressorCurrent, closedLoopControl, compressorCurrentTooHighFault, compressorShortedFault, compressorNotConnectedFault):
    builder.Prep(8, 24)
    builder.Pad(4)
    builder.PrependBool(compressorNotConnectedFault)
    builder.PrependBool(compressorShortedFault)
    builder.PrependBool(compressorCurrentTooHighFault)
    builder.PrependBool(closedLoopControl)
    builder.PrependFloat64(compressorCurrent)
    builder.Pad(2)
    builder.PrependBool(pressureSwitchValve)
    builder.PrependBool(enabled)
    builder.PrependInt32(module)
    return builder.Offset()
